- name: deploy a windows 2019 server in openshift 
  hosts: localhost
  tasks:
    - name: Create a VM
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: supertestvm
            annotations:
              description: some kind of vm
            labels:
              app: supertestvm
              os.template.kubevirt.io/fedora36: 'true'
            namespace: kubevirt-project
          spec:
            running: true
            template:
              metadata:
                annotations:
                  vm.kubevirt.io/flavor: small
                  vm.kubevirt.io/os: fedora36
                  vm.kubevirt.io/workload: server
                labels:
                  kubevirt.io/domain: supertestvm
                  kubevirt.io/size: small
              spec:
                domain:
                  cpu:
                    cores: 1
                    sockets: 1
                    threads: 1
                  devices:
                    disks:
                      - disk:
                          bus: virtio
                        name: rootdisk
                      - disk:
                          bus: virtio
                        name: cloudinitdisk
                    interfaces:
                      - masquerade: {}
                        model: virtio
                        name: default
                    networkInterfaceMultiqueue: true
                    rng: {}
                  features:
                    acpi: {}
                    smm:
                      enabled: true
                  firmware:
                    bootloader:
                      efi: {}
                  machine:
                    type: q35
                  resources:
                    requests:
                      memory: 2Gi
                hostname: supertestvm
                networks:
                  - name: default
                    pod: {}
                terminationGracePeriodSeconds: 180
                volumes:
                  - name: rootdisk
                    containerDisk:
                      image: 'quay.io/containerdisks/fedora:36'
                  - cloudInitNoCloud:
                      userData: |-
                        #cloud-config
                        users:
                          - name: fedora
                            ssh-authorized-keys:
                              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDjymj3M1LmAEUcw2v7e6muiyclnWDbjY53jBR/9L2L2 matt@bb41.lab.cheeseburgia.com
                    name: cloudinitdisk
          
    - name: add service for http
      redhat.openshift.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: kubevirt-project
            name: supertestvm-service
            labels:
              app: supertestvm
          spec:
            selector:
              app: supertestvm
            type: ClusterIP
            ports:
            - name: http
              protocol: TCP
              port: 80
              targetPort: 80
          
#   - name: add service for ssh
#     redhat.openshift.k8s:
#       definition:
#         apiVersion: route.openshift.io/v1
#         kind: Route
#         metadata:
#           name: supertestvm-route
#         spec:
#           port:
#             targetPort: ssh
#           tls:
#             termination: edge
#             insecureEdgeTerminationPolicy: Redirect
#           to:
#             kind: Service
#             name: supertestvm
#             weight: 100
#           wildcardPolicy: None
