---

- name: deploy James's web stack
  hosts: localhost
  tasks:
    - name: Define resources
      kubernetes.core.k8s:
        wait: true
        state: "{{ infra_state | default('present') }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='./jh-stack/') }}"
