---

- name: deploy James's web stack
  hosts: localhost
  tasks:
    - name: Define resources
      redhat.openshift.k8s:
        state: present
        definition: "{{ lookup('redhat.openshift.kustomize', dir='./from-jharm/') }}"

    - name: database
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            namespace: kubevirt-project
            labels:
              app: database
            name: database
          spec:
            running: true
            dataVolumeTemplates:
            - apiVersion: cdi.kubevirt.io/v1beta1
              kind: DataVolume
              metadata:
                creationTimestamp: null
                name: database
              spec:
                source:
                  http:
                    url: https://s3.us-east.cloud-object-storage.appdomain.cloud/roadshowocpvirt/database.qcow2
                storage:
                  resources:
                    requests:
                      storage: 16Gi
                  volumeMode: Block
            template:
              metadata:
                labels:
                  app: database
                  kubevirt.io/domain: database
              spec:
                domain:
                  cpu:
                    cores: 1
                    sockets: 2
                    threads: 1
                  devices:
                    disks:
                    - disk:
                        bus: virtio
                      name: rootdisk
                    interfaces:
                    - masquerade: {}
                      name: default
                  resources:
                    requests:
                      memory: 8Gi
                evictionStrategy: LiveMigrate
                networks:
                - name: default
                  pod: {}
                volumes:
                - dataVolume:
                    name: database
                  name: rootdisk

    - name: winweb
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            namespace: kubevirt-project
            labels:
              app: winweb
            name: winweb01
          spec:
            running: true
            dataVolumeTemplates:
            - apiVersion: cdi.kubevirt.io/v1beta1
              kind: DataVolume
              metadata:
                creationTimestamp: null
                name: winweb01
              spec:
                source:
                  http:
                    url: https://s3.us-east.cloud-object-storage.appdomain.cloud/roadshowocpvirt/winweb01.qcow2
                storage:
                  resources:
                    requests:
                      storage: 90Gi
                  volumeMode: Block
            template:
              metadata:
                labels:
                  app: winweb
                  kubevirt.io/domain: winweb01
              spec:
                domain:
                  cpu:
                    cores: 1
                    sockets: 4
                    threads: 1
                  clock:
                    timer:
                      hpet:
                        present: false
                      hyperv: {}
                      pit:
                        tickPolicy: delay
                      rtc:
                        tickPolicy: catchup
                  features:
                    acpi: {}
                    apic: {}
                    hyperv:
                      frequencies: {}
                      ipi: {}
                      relaxed: {}
                      reset: {}
                      runtime: {}
                      spinlocks:
                        spinlocks: 8191
                      synic: {}
                      synictimer:
                        direct: {}
                      tlbflush: {}
                      vapic: {}
                      vpindex: {}
                    smm:
                      enabled: true
                  firmware:
                    bootloader:
                      efi: {}
                  machine:
                    type: pc-q35-rhel8.6.0
                  devices:
                    disks:
                    - disk:
                        bus: sata
                      name: rootdisk
                    interfaces:
                    - masquerade: {}
                      model: e1000e
                      name: default
                    inputs:
                    - name: tablet
                      bus: usb
                      type: tablet
                  resources:
                    requests:
                      memory: 8Gi
                evictionStrategy: LiveMigrate
                networks:
                - name: default
                  pod: {}
                volumes:
                - dataVolume:
                    name: winweb01
                  name: rootdisk


    - name: mysql service
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: kubevirt-project
            name: database
          spec:
            selector:
              app: database
            type: ClusterIP
            ports:
            - name: mysql
              protocol: TCP
              port: 3306
              targetPort: 3306

    - name: http service
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: kubevirt-project
            name: winweb
          spec:
            selector:
              app: winweb
            type: ClusterIP
            ports:
            - name: http
              protocol: TCP
              port: 80
              targetPort: 80

    - name: http service
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            namespace: kubevirt-project
            name: php-webapp
          spec:
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            to:
              kind: Service
              name: winweb
              weight: 100
            wildcardPolicy: None
