---

- name: deploy James's web stack
  hosts: localhost
  tasks:
    - name: Define resources
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('kubernetes.core.kustomize', dir='./from-jharm/') }}"
